### ISSUE TITLE
tab-reloader disappeared 

### ISSUE THREAD

**Issue by vickstix** [james-fray/tab-reloader#10]
It just disappeared off the menu bar. I disabled it and re-enabled it. Also removed it, and reinstalled it, but it still won't come back. :-( Any ideas how to get it to show up again?

**Comment by WaXXtm** [comment]
2 issues in Firefox x64 version 50.1.0:
1. The buttton's icon now invisible but the button is still there, once you enable a tab a number shows.
2. Settings for each tab are no longer remembered after you close Firefox and have to be set up every time you restart Firefox - all worked really well before the update on 17 Dec 2016 version 0.1.7.1.

**Comment by james-fray** [comment]
What is your Firefox version? Tab Reloader moved to WebExtension.

**Comment by james-fray** [comment]
For Firefox version < 50, it is recommend to switch to 0.16; https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/versions/

**Comment by WaXXtm** [comment]
I'm using Firefox 50.1.0 x64 running on Windows 10 Pro x64 1607.14393.576
Thanks for the link to 0.1.6, I will use that for now.

**Comment by james-fray** [comment]
I am submitting a new version. Let me know if the issue is fixed or not

**Comment by WaXXtm** [comment]
Thanks - I see version 0.1.8 in the version list, as soon as I can install it I will let you know

**Comment by WaXXtm** [comment]
I have 0.1.8 now and the behaviour is identical to 0.1.7.1
1. Invisible icon
2. Numbered box shows when some tabs are set
3. Does not remember settings when Firefox is closed and opened the next time.

Screen-grabs attached from versions 0.1.6 (working well) and 0.1.8 (with and without tabs set)
0.1.6 remembers settings when Firefox is opened the next time.

![tab_reloader_0_1_8-2](https://cloud.githubusercontent.com/assets/24630569/21352897/875dfcd6-c6bb-11e6-941c-dd18568acd36.jpg)
![tab_reloader_0_1_6-](https://cloud.githubusercontent.com/assets/24630569/21352898/875f8a1a-c6bb-11e6-8618-bb382517b3ca.jpg)
![tab_reloader_0_1_8-1](https://cloud.githubusercontent.com/assets/24630569/21352899/8764796c-c6bb-11e6-837b-9443835fa354.jpg)

**Comment by jamieSquid** [comment]
Ditto for me.
Windows 10 with latest updates
FF 50.1
Tab Reloader 0.1.8

**Comment by Banditz71** [comment]
Same here......
Win 7
FF 50.1
Tab Reloader 0.1.8

**Comment by james-fray** [comment]
Okay the problem is the extension works just fine in the developer mode, but when it gets signed it is not working anymore;

Anyhow I think the latest commit should have fixed these issues, please give it a try and let me know if you are still experiencing the issue

https://github.com/james-fray/tab-reloader/archive/master.zip

To test, open "about:debugging" in a browser tab,
Unpack the downloaded ZIP file
Point "Load Temporary Addon" to the "manifest.json" inside the src folder.

The extension icon should appear in the toolbar and the extension should work as expected. The only issue is that the extension is not available after restart, so to test the session restoring feature, press the reload button in the "about:debugging" and wait for 10 seconds until tabs are restored.

**Comment by WaXXtm** [comment]
Thanks for your work here - version 0.1.9 has now been 'released' by Mozilla.

This has certainly fixed the disappearing icon.

However, the tab settings are still not being remembered once Firefox is closed and all tabs you want to auto-reload must be set again each time you open Firefox.

Back to 0.1.6 again.

**Comment by WaXXtm** [comment]
Interestingly, when I go back to 0.1.6, all the tab reload settings are picked up straight away.
