### ISSUE TITLE
Asterix mapping not working for URL

### ISSUE THREAD

**Issue by orschiro** [james-fray/tab-reloader#65]
Hi guys, 

I was hoping for the following to work:

        "url": "app.hubspot.com/live-messages/*"

But it's not matching any URLs that would be replaced by the asterix (*).

Anyone ideas?

**Comment by james-fray** [comment]
Why don't you set a reloading job for the entire hostname (`app.hubspot.com`), then use policies to only match `/live-messages/*` path. See https://add0n.com/tab-reloader.html#faq14

**Comment by james-fray** [comment]
Please reopen if it doesn't work for you.

**Comment by orschiro** [comment]
Thank you!

Something like this?

[image: image.png]

**Comment by orschiro** [comment]
@james-fray Thank you!

Something like this?

![image](https://user-images.githubusercontent.com/170947/90017558-008dcc80-dcac-11ea-9df8-6c9b02dccfb7.png)

**Comment by james-fray** [comment]
This should work:

```json
{
  "app.hubspot.com": "live-messages"
}
```

**Comment by orschiro** [comment]
Thanks but it's still matching the following two URLs:

- https://app.hubspot.com/contacts/5756448/lists
- https://app.hubspot.com/live-messages/5756448/inbox/397800291#reply-editor

This is my custom jobs entry:

```
  {
    "current": true,
    "dd": 0,
    "hh": 0,
    "hostname": "app.hubspot.com",
    "mm": 30,
    "ss": 0
  },
```

And this my reloading policy:

```
{
  "app.hubspot.com": "live-messages"
}
```

**Comment by rNeomy** [comment]
Policies are checked just before the actual reloading occurs. So the pages that do not match with the policy object will not get reloaded (being skipped)

**Comment by orschiro** [comment]
I see, thanks! 

Although the extension icon shows the page as active (coloured red), right?

**Comment by orschiro** [comment]
We are all good on this one. Thanks!

**Comment by orschiro** [comment]
@james-fray sorry to bring this up again but it's still not working.

It's triggering on the following two URLs but it should only trigger on the first one:

1. https://app.hubspot.com/live-messages/5756448/inbox/427037901#reply-editor
2. https://app.hubspot.com/email/5756448/edit-dd/34838292990/content

Any idea why?

![image](https://user-images.githubusercontent.com/170947/92924597-85017580-f439-11ea-9fb8-9fc8b5989a3a.png)

**Comment by megamorphg** [comment]
I can't get this method to work either. I'm using Firefox.
![image](https://user-images.githubusercontent.com/1782353/165561556-306c6556-ff60-4914-b95f-1f6951b6a388.png)

I'm guessing we have to use the "URL" value instead with a regex?

**Comment by madduck** [comment]
I am also struggling with this. I want to set a rule for subpages of `https://www.squash.org.nz/sit/*`, and ideally not maintain two separate JSON objects for the same policy, so I tried:

```
[{"url": "*squash.org.nz/sit/*", …}]
```

But that does not trigger.

@megamorphg your post is missing the important part of how you got it working! That's mean! ;)

**Comment by madduck** [comment]
@megamorphg okay, but this is a reload policy, so it would require *also* a custom job to be defined, which I think is redundant, but more on that later. I was trying to use the `url` keyword in the custom job JSON, because the description suggested it would be possible:

![image](https://user-images.githubusercontent.com/195073/166846222-8c70df50-ab3e-495b-adb2-9fc4a6f69c5b.png)

Thanks to you, I now have it working, with the following custom job:

```
[
  {
    "hostname": "*squash.org.nz",
    "dd": 0,
    "hh": 0,
    "mm": 11,
    "ss": 0
  }
]
```

and here is the required reload policy:

```
{
  "*squash.org.nz": {
    "url": "^\/sit\/"
  }
}
```

I have two low-hanging fruits on how to make this better, but I'll also open a new issue to suggest that the reload policies be folded into the custom jobs. Watch this space.

1. It would be good if `/` wasn't treated as a special character in the URL regexp, given that `/` is an integral component of URLs;
2. The docs might want to be a bit clearer about the `url` field, which seems to match not the URL, but only the path.

**Comment by james-fray** [comment]
The next release improves URL matching support. See https://add0n.com/tab-reloader.html?v5#faq11

**Comment by megamorphg** [comment]
> The next release improves URL matching support. See https://add0n.com/tab-reloader.html?v5#faq11

Ah, that makes it much simpler, no need for a reloading policy any more. Will Firefox users also get this update?

**Comment by james-fray** [comment]
@megamorphg, unfortunately not! The 0.5.x is based on service workers, and FF does not yet support this type!
